### ISSUE TITLE
Cancel appointment should make sure shelf_expire_time is in future

### ISSUE THREAD

**Issue by eby** [aadl/arborcat#135]
A patron can currently schedule pickups out farther than the shelf expire would normally allow. 

We are occasionally getting patrons that cancel their appointment and have the shelf_expire set to what it would have been which can be today/yesterday/in the past. This prevents them from being able to reschedule.

Canceling should probably set shelf_expire_time to the normal date or 1 or 2 days in the future if the expire is going to be in the past.

**Comment by lauriek334** [comment]
Made change to the pickup appointment cancel functiuonality to check that the holdShelfExpireTime is > tomorrow, if not, the holdShelfExpireTime is set to tomorrow. Created Pull Request #137

**Comment by lauriek334** [comment]
This was deployed to prod on Sept. 8th.
