### ISSUE TITLE
Logged out users can get redirected to a user account on appointment submission

### ISSUE THREAD

**Issue by eby** [aadl/arborcat#136]
From dev discussion:

```
/var/log/nginx/access.log.1:99.59.193.20 - - [02/Sep/2020:12:04:36 -0400] "POST /pickuprequest/10067758/808fef24885c836435e824f62e53f1b4/105 HTTP/2.0" 303 338 "https://aadl.org/pickuprequest/10067758/808fef24885c836435e824f62e53f1b4/105" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-" "aadl.org" sn="aadl.org" rt=3.237 ua="unix:/run/php/php7.2-fpm.sock" us="303" ut="3.236" ul="358" cs=-
/var/log/nginx/access.log.1:99.59.193.20 - - [02/Sep/2020:12:04:37 -0400] "GET /user/0 HTTP/2.0" 403 6001 "https://aadl.org/pickuprequest/10067758/808fef24885c836435e824f62e53f1b4/105" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-" "aadl.org" sn="aadl.org" rt=0.114 ua="unix:/run/php/php7.2-fpm.sock" us="403" ut="0.112" ul="20214" cs=-
```

Users that submit an appointment should get a confirmation if they aren't logged in vs being redirected. This one also didn't seem to create an appointment but I'll dig more into that.

**Comment by lauriek334** [comment]
I've fixed the redirect for anonymous users so a 403 error is not thrown. Created Pull request for Eric and Troy to review

**Comment by lauriek334** [comment]
Need to work further on the confirmation UI.
I'm thinking an information banner at the top which displays the following:
           FOR LOGGED IN USERS: 'See the Scheduled Pickup Appointments section in your account', 'information'
           FOR ANONYMOUS USERS: 'Log in to see your scheduled pickup appointments', 'information'
What do you think?

**Comment by taleon** [comment]
So I don't think we need to change anything if there is currently a logged in user for the banner display. Staff will go back to their own account page, but that's okay for now.

For logged out users I think a drupal messenger banner with "Your appointment has been scheduled for {{ location }}. Log in to see your scheduled pickup appointments."
