### ISSUE TITLE
First in line designation.

### ISSUE THREAD

**Issue by eby** [aadl/arborcat#166]
Some background:

The hold queue position is based on when they placed the hold for our setup. First placed, first out.

We have an option that is called "top of the queue" but in the background is actually called "cut in line". When you hit this option it just sets cut_in_line = true. When an item is scanned it looks for anyone who has cut in line set and fills those first without looking at the normal queue. So the "queue" isn't really involved.

We don't want the number changing on other patrons so the 1 of X should stay the same. However if we see cut in line set to true we should display something like 'First in Line' or whatever fits for the specific patron in question so they know it worked when staff said they did it.

**Comment by taleon** [comment]
This is an API / frontend thing. Already have on list for improvements pass I'm looking to do mid this week.
