### ISSUE TITLE
Review Form Always Built

### ISSUE THREAD

**Issue by eby** [aadl/arborcat#180]
This is related to #179 as we are building the review form for anonymous users, even though the theme doesn't display it.

It is probably good that the theme is doing the gatekeeping, but we should most likely do more checks in the backend to prevent needless queries.

https://github.com/aadl/arborcat/blob/a994f72945921282b254ac0879970e7331846ff9/src/Controller/DefaultController.php#L164

**Comment by lauriek334** [comment]
Address this issue - arborcat has been updated on pinkeye. See branch https://github.com/aadl/arborcat/tree/issues179_180_181
