### ISSUE TITLE
view_user_list doesn’t handle linking to a deleted list

### ISSUE THREAD

**Issue by eby** [aadl/arborcat#181]
The following code:

https://github.com/aadl/arborcat/blob/a994f72945921282b254ac0879970e7331846ff9/arborcat_lists/src/Controller/DefaultController.php#L131-L142

ends up causing multiple drupal errors (public, uid, title etc doesn’t exist / non-object). We should wrap this up with something that gives a nicer page to patrons.

**Comment by lauriek334** [comment]
Not sure how to test this  - as it's not clear to me how a deleted listID can be passed to this method.  Added an explicit check that the list has been returned from the DB request before trying to access properties of the list object.

arborcat has been updated on pinkeye. See branch https://github.com/aadl/arborcat/tree/issues179_180_181
