### ISSUE TITLE
need to get some other sort options implemented

### ISSUE THREAD

**Issue by ulotrichous** [aadl/arborcat#21]
Do we have date added in the index and pub date too?  If we could have these sort options, that would be big:

Relevance
Just Added
Alphabetical
Pub Year: Oldest First
Pub Year: Newest First
Alpha by Author

**Comment by taleon** [comment]
Yea, that's on my list for the weekend. Alpha by author I'm not sure about yet.

**Comment by ulotrichous** [comment]
Alpha by author probably the least important of these. just added and pub year most important, esp. for staff.

**Comment by taleon** [comment]
all in
