### ISSUE TITLE
Last page of results includes previously paged items to make the page view total

### ISSUE THREAD

**Issue by ulotrichous** [aadl/arborcat#25]
cf. https://migrate.aadl.org/arborelastic/catalog/*?mat_code=r%2Cp&gridview=false&page=0
and then https://migrate.aadl.org/arborelastic/catalog/*?mat_code=r%2Cp&gridview=false&page=1

Hits are numbered right, but it's pulling the last 25 results instead of 26-31.

**Comment by taleon** [comment]
Hmm. Will have to look at the arborelastic module to see where this is happening.
