### ISSUE TITLE
Sort order dropdown in catalog does not reflect URL args

### ISSUE THREAD

**Issue by ulotrichous** [aadl/arborcat#49]
It works, but patrons think it doesn't because the dropdown resets to relevance.

**Comment by taleon** [comment]
Really? Is this working as expected on your end? Mine changes based on the url arguments.

**Comment by ulotrichous** [comment]
Just added is the only one that sticks for me when I choose it?

**Comment by taleon** [comment]
Hmmm. Alright, I'll dig.
