### ISSUE TITLE
Author that appears in Author field for DVD checkouts / requests is not indexed as author

### ISSUE THREAD

**Issue by ulotrichous** [aadl/arborcat#59]
cf. https://aadl.org/user/89487

Click any of the authors in the author column on holds, mostly directors or stars. None come up with results, notably not the result it appeared associated with. I think maybe the additional authors field is not indexed as author?

**Comment by taleon** [comment]
These will be removed with an update I'm rolling out. We never displayed author for dvds/blu-rays before anyway.
