### ISSUE TITLE
Series Search can't handle ?

### ISSUE THREAD

**Issue by ulotrichous** [aadl/arborcat#61]
cf.  https://aadl.org/catalog/record/10044491

Series link works and is cataloged, but has a ? so breaks the search term expression.

Description: Catalog search feedback from a patron

She was looking for a way to find more titles in a kids' nonfiction series.
The titles in the series are called things like "Who Was Andy Warhol," Who Is
JK Rowling," "What Is the Panama Canal," "What Was the Ice Age." Under the
Ice Age title, there is a series link, "Who Was" but it doesn't work - it
says there are no search results. Here's that record:
https://aadl.org/catalog/record/10044491

That series link would be a very helpful solution for this problem of a
series with a variety of authors and titles.

Just bringing it to your attention, thanks.

**Comment by taleon** [comment]
fix going out today
